# Generated by Django 4.2 on 2023-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
